# Generated by Django 3.1.7 on 2021-04-09 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ItemList',
            fields=[
                ('itemSerial', models.IntegerField(primary_key=True, serialize=False)),
                ('itemName', models.CharField(max_length=50)),
                ('itemCategory', models.CharField(max_length=10)),
                ('itemPrice', models.FloatField()),
            ],
        ),
    ]
