# Generated by Django 3.1.7 on 2021-04-09 23:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apitest', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ItemList',
            new_name='Items',
        ),
    ]
