# Generated by Django 3.1.7 on 2021-04-09 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apitest', '0002_auto_20210410_0531'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='items',
            name='itemSerial',
            field=models.IntegerField(),
        ),
    ]
