# Generated by Django 3.1.7 on 2021-04-09 23:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apitest', '0003_auto_20210410_0550'),
    ]

    operations = [
        migrations.RenameField(
            model_name='items',
            old_name='itemSerial',
            new_name='itemId',
        ),
    ]
